name: Build and Release BSummarize

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Node.js 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Get Current Version
        id: get-current-version
        run: |
          echo "::set-output name=version::$(jq -r '.version' manifest.json)"
        working-directory: ./

      - name: Increment Version
        id: increment-version
        uses: actions/github-script@v6
        with:
          script: |
            const manifest = require('./manifest.json');
            const currentVersion = manifest.version;
            const versionParts = currentVersion.split('.');
            versionParts[2] = parseInt(versionParts[2], 10) + 1;
            const newVersion = versionParts.join('.');
            core.setOutput('new-version', newVersion);

      - name: Update Manifest Version
        run: |
          echo "New version: ${{ steps.increment-version.outputs.new-version }}"
          jq --arg newVersion "${{ steps.increment-version.outputs.new-version }}" '.version = $newVersion' manifest.json > manifest.tmp.json && mv manifest.tmp.json manifest.json
        working-directory: ./

      - name: Commit and Push Updated Manifest
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add manifest.json
          git commit -m "Bump version to ${{ steps.increment-version.outputs.new-version }}"
          git push
        working-directory: ./
      - name: Lint Extension
        run: web-ext lint
        working-directory: ./

      - name: Package Extension
        run: web-ext build --overwrite-dest --filename=bsummarize.xpi --verbose
        working-directory: ./

      - name: Save Version to File
        run: echo "${{ steps.increment-version.outputs.new-version }}" > new_version.txt
        working-directory: ./

      - name: Upload Version Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-artifact
          path: ./new_version.txt

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bsummarize-extension
          path: ./web-ext-artifacts/bsummarize.xpi

  create-release:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version-artifact

      - name: Read Version from File
        id: read-version
        run: |
          NEW_VERSION=$(cat new_version.txt)
          echo "::set-output name=new-version::$NEW_VERSION"

      - name: Download Extension Artifact
        uses: actions/download-artifact@v4
        with:
          name: bsummarize-extension
          path: ./web-ext-artifacts/

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ steps.read-version.outputs.new-version }}
          name: BSummarize Release v${{ steps.read-version.outputs.new-version }}
          draft: false
          prerelease: false
          files: ./web-ext-artifacts/bsummarize.xpi
          generate_release_notes: true
          token: ${{ secrets.TOKEN }}
