name: Build and Release Firefox Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Read version from manifest
        id: read_version
        run: |
          version=$(jq -r '.version' manifest.json)
          echo "::set-output name=version::$version"

      - name: Package extension (xpi)
        run: |
          web-ext build --overwrite-dest --source-dir . --artifacts-dir ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_version.outputs.version }}
          release_name: Release v${{ steps.read_version.outputs.version }}
          draft: false
          prerelease: false
          files: ./artifacts/*.xpi

      - name: Bump version
        id: bump_version
        run: |
          current_version=${{ steps.read_version.outputs.version }}
          IFS="." read -a version_parts <<< "$current_version"
          version_parts[2]=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          jq --arg new_version "$new_version" '.version = $new_version' manifest.json > manifest_tmp.json
          mv manifest_tmp.json manifest.json

      - name: Commit updated manifest
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add manifest.json
          git commit -m "Bump version to $new_version"
          git push origin main
